# Generated by Django 3.1.5 on 2021-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sampham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tên sản phẩm')),
                ('sodienthoai', models.CharField(blank=True, max_length=10, null=True)),
                ('diachi', models.CharField(blank=True, max_length=9999, null=True)),
            ],
        ),
    ]
